<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="simple_arm">

  <ros2_control name="simple_arm_ros2_control" type="system">
    <hardware>
      <plugin>ign_ros2_control/IgnitionSystem</plugin>
    </hardware>
    <joint name="joint1">
      <command_interface name="position">
        <param name="min">-1</param>
        <param name="max">1</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="joint2">
      <command_interface name="position">
        <param name="min">-1</param>
        <param name="max">1</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="joint3">
      <command_interface name="position">
        <param name="min">-1</param>
        <param name="max">1</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
  </ros2_control>

  <gazebo>
    <plugin filename="libign_ros2_control-system.so" name="ign_ros2_control::IgnitionROS2ControlPlugin">
      <parameters>$(find simple_arm)/config/simple_arm_controllers.yaml </parameters>
    </plugin>
  </gazebo>

  <xacro:property name="mass" value="1"/>
  <xacro:property name="width" value="0.1"/>
  <xacro:property name="height" value="1"/>

  <link name="world"/>

  <joint name="fixed_base" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="base_link"/>

  <joint name="joint0" type="fixed">
    <parent link="base_link"/>
    <child link="link0"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="link0">
    <visual>
      <geometry>
        <box size="${width} ${width} ${width}"/>
      </geometry>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <inertial>
      <origin xyz="0 0 ${width/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass/12.0 * (width*width + width*width)}" ixy="0.0" ixz="0.0"
        iyy="${mass/12.0 * (width*width + width*width)}" iyz="0.0"
        izz="${mass/12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="joint1" type="revolute">
    <parent link="link0"/>
    <child link="link1"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit effort="100" velocity="1.0" upper="1.6" lower="-1.6"/>
  </joint>

  <link name="link1">
    <visual>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height}"/>
      </geometry>
      <material name="green">
        <color rgba="0 1 0 1"/>
      </material>
    </visual>
    <inertial>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass/12.0 * (width*width + height*height)}" ixy="0.0" ixz="0.0"
        iyy="${mass/12.0 * (height*height + width*width)}" iyz="0.0"
        izz="${mass/12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="joint2" type="revolute">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 ${height}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit effort="100" velocity="1.0" upper="1.6" lower="-1.6"/>
  </joint>

  <link name="link2">
    <visual>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 1 1"/>
      </material>
    </visual>
    <inertial>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass/12.0 * (width*width + height*height)}" ixy="0.0" ixz="0.0"
        iyy="${mass/12.0 * (height*height + width*width)}" iyz="0.0"
        izz="${mass/12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="joint3" type="revolute">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0 0 ${height}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit effort="100" velocity="1.0" upper="1.6" lower="-1.6"/>
  </joint>

  <link name="link3">
    <visual>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height}"/>
      </geometry>
      <material name="red">
        <color rgba="1 0 0 1"/>
      </material>
    </visual>
    <inertial>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass/12.0 * (width*width + height*height)}" ixy="0.0" ixz="0.0"
        iyy="${mass/12.0 * (height*height + width*width)}" iyz="0.0"
        izz="${mass/12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="tool_joint" type="fixed">
    <origin xyz="0 0 1" rpy="0 0 0"/>
    <parent link="link3"/>
    <child link="tool_link"/>
  </joint>

  <link name="tool_link">
  </link>

</robot>
